### ISSUE TITLE
Incorrect definition of Landeau Density? 

### ISSUE THREAD

**Issue by LaribiHakima** [ben-ix/harmonicmeanp#1]
Hello, thank's a lot for the provided code! 

In the implementation of _landeau_density, shouldn't the method return **1 / (pi * sigma) * integral** rather than  **1 / (mu * sigma) * integral** ?

**Comment by benjaminpatrickevans** [comment]
Hi @LaribiHakima, thanks for spotting! You are correct. I will fix that
